baseURL = "https://chaoyuezhao.github.io"
title = "超越的主页"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = "zhaochaoyue"
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "zh"

[params.info]
description = "道义是天际的星光，科学是指路的灯火"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "超越"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006-01-02"
listDateFormat = ""
hideEntryNavigation = ["page"] # boolean / array of sections
recentPostsLength = 5
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = false
homepageSections = ["recent_posts"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "zcy521" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
codepen = "Chaoyue"
email = "me@zhaochaoyue.com"
github = "ChaoyueZhao"
twitter = "ZCY521"

[params.social.config]
platforms = ["github","twitter","email","codepen"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.zh]
lang = "zh"
languageName = "Chinese"
weight = 1
